sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: rxyxh8nYdYY1nmfy0sf3p2tnJytZMES6k2MvsSqmIjC0BUqjPX97gHvpX14l0e7l/X7fpJORcD8DZbmfuc98v/9GkVAPypQr9mgw41G8la+Wlbu/jWJiRiqAfjBSmlADx7OBaIFGfkwU9eNzASRQqjeoLqEhRt70gQGO14LV9Xwrxsira08KYQJ345+8Z7l9rmu8rxXc/utB7AtAIksRnWujRU5Zdu0MeC77rYhysip5KMDzanqY8JLnzkJdVRqRIHthKabZ1MlI7s3CGN8W90aWl4Fq/kBLzsmTdEYOCk5SpECHd67Z9Te/QXkCXqzaMr5YkloNexn6kWqxZM0wHUTfSYOKnGIxpSL+US2b3SnbQrHabticHudt7ybqcqAaHbYTItgnYcbYgNYhc8RRFzAnSxaQqLvoup+c7ONOqxsNaqwDJIsv5ljHHYWDMp7+rm4uw3P9Lc7Npmm3oSGyIXQUQa3ECcWdOvWBswBh12k1XYwt15jVaozN/ngGTSi8c8oFLiYbx+eHO2bp6/hgjFmanR0mLDf3y5ofuseX9RByNzIs7ufRVfYIvjyuSvGB/VIa5OY/MGDWs9siYq05pzrf2DxDFYxPHiH6BZBrkuNjtKkYSkU6JGzaGq7WjMjAHopzb8VA+hDlQpse6yq0+oflOgKL03/if4dQ5wYs9xo=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Stories-of-a-Western-Town_2949
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy